import type { GeneratorType, GeneratorParams } from "../types";

export const DEFAULT_PARAMS: Record<GeneratorType, GeneratorParams> = {
  ai: {},
  bsp: {
    minPartitionSize: 6,
    maxDepth: 4,
    minRoomSize: 3,
    padding: 1,
    addDoors: true,
    addFeatures: true,
    addFurniture: false,
    furnitureDensity: 0.15,
    rubbleChance: 0,
    collapsedChance: 0,
    fallenColumnChance: 0,
    // Room shapes - default to rectangle only
    useRectangle: true,
    useComposite: false,
    useTemplate: false,
    useCellular: false,
    usePolygon: false,
    // Modifiers
    useNibbleCorners: false,
    useAddAlcoves: false,
    useRoundCorners: false,
    useAddPillars: false,
  },
  cave: {
    iterations: 3,
    initialFillProbability: 0.5,
    addFeatures: true,
    addFurniture: false,
    furnitureDensity: 0.15,
    rubbleChance: 0,
    collapsedChance: 0,
    fallenColumnChance: 0,
  },
  dla: {
    fillPercentage: 0.35,
    stickiness: 0.8,
    spawnMode: "edge",
    addFeatures: false,
    addFurniture: false,
    furnitureDensity: 0.15,
    rubbleChance: 0,
    collapsedChance: 0,
    fallenColumnChance: 0,
  },
  wfc: {
    seedRadius: 5,
  },
  drunkard: {
    fillPercentage: 0.45,
  },
  "drunkard-weighted": {
    fillPercentage: 0.45,
  },
  "drunkard-multi": {
    fillPercentage: 0.45,
    numWalkers: 6,
  },
  maze: {
    addStartEnd: true,
    loopChance: 0,
    openness: 0,
  },
  "maze-prims": {
    addStartEnd: true,
    loopChance: 0,
    openness: 0,
  },
  "maze-division": {
    addStartEnd: true,
    loopChance: 0,
    openness: 0,
  },
  perlin: {
    scale: 0.08,
    octaves: 4,
    persistence: 0.5,
    lacunarity: 2,
    waterLevel: 0.35,
    sandLevel: 0.4,
    grassLevel: 0.6,
    forestLevel: 0.75,
    islandMode: true,
    islandFalloff: 1.8,
    erosionIterations: 2,
  },
  "perlin-continent": {
    scale: 0.04,
    octaves: 4,
    persistence: 0.5,
    lacunarity: 2,
    waterLevel: 0.35,
    sandLevel: 0.4,
    grassLevel: 0.6,
    forestLevel: 0.75,
    islandMode: false,
    islandFalloff: 1.8,
    erosionIterations: 2,
  },
  voronoi: {
    numRooms: 8,
    minRoomDistance: 4,
    relaxation: 2,
    addDoors: true,
    addFeatures: false,
    addFurniture: false,
    furnitureDensity: 0.15,
    rubbleChance: 0,
    collapsedChance: 0,
    fallenColumnChance: 0,
  },
  hybrid: {
    splitDirection: "diagonal",
    blendMode: "soft",
    blendWidth: 4,
    connectRegions: true,
    addFeatures: false,
    addFurniture: false,
    furnitureDensity: 0.15,
    rubbleChance: 0,
    collapsedChance: 0,
    fallenColumnChance: 0,
  },
  "hybrid-radial": {
    splitDirection: "radial",
    blendMode: "soft",
    blendWidth: 6,
    connectRegions: true,
    addFeatures: false,
    addFurniture: false,
    furnitureDensity: 0.15,
    rubbleChance: 0,
    collapsedChance: 0,
    fallenColumnChance: 0,
  },
};
